import React from 'react'
import '../../styles/card2.css';

export default function Card2(props) {
    return (
            <div className="mcard2">
                <div className="mcard2-content">
                    <div className="mcard2-img">
                        <img src={props.src} alt="..."/></div>
                    <div className="mcard2-title">
                        <h4><span>{props.title}</span></h4>
                    </div>
                </div>
                
                <p>
                Eduvance offers EnablAR's DIY Hologram kits. Students can get exposure to the exiting world of holograms by building their own hologram pyramids. Teachers can give their students DIY Hologram kits to explore apps generated by EnablAR.
                </p>
            </div>
    )
}
